name: kgk_dia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_bloc: ^8.1.3

  # Data
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2

  # Utils
  uuid: ^4.3.3
  equatable: ^2.0.5
  intl: ^0.19.0
  cron: ^0.6.0
  connectivity_plus: ^6.0.5
  excel:
  file_picker:

  # Firebase
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.3
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.1.11

  # UI
  cupertino_icons: ^1.0.6
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  # For generating app icons

flutter:

  uses-material-design: true

  assets:
    - assets/testdata.xlsx
    - assets/kgk.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/kgk.png"
